{ pkgs, ... }:
{
  home.packages = with pkgs; [
    # --- Rust ---
    rustup # Rust toolchain installer
    bacon # Background rust code checker
    cargo-info # Cargo subcommand to show crates info from crates.io
    rusty-man # Command-line viewer for documentation generated by rustdoc
  ];
}
