[General]
historyWindowHeight=1
historyWindowWidth=1

[quickshell]
currentWallpaper=/home/Prizrak/Pictures/Wallpapers/94ae229f-168b-422e-adbe-ba024602ad8d.png
profileImage=/home/Prizrak/face
randomWallpaperFlag=false
showActiveWindowIconFlag=true
showMediaInBarFlag=true
showSystemInfoInBarFlag=true
transitionDuration=1.1
transitionFps=360
transitionType=random
useSWWWFlag=false
useWallpaperThemeFlag=false
videoPath=~/Videos/
visualizerType=fire
wallpaperFolder=/home/Prizrak/Pictures/Wallpapers
wallpaperInterval=60
wallpaperResize=crop
weatherCity=Dinslaken
weatherTempUnit=celsius
